services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb-container
    restart: always
    env_file: 
      - .env
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress-container
    restart: always
    env_file: 
      - .env
