services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
  wordpress:
    build: ./requirements/wordpress
  mariadb:
    build: ./requirements/mariadb

volumes:
  database:
  wordpress: