volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/sschelti/data/wordpress
      o: bind
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/sschelti/data/mariadb
      o: bind

networks:
  inception:
    name: inception

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    restart: always
    pull_policy: build
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    restart: always
    pull_policy: build
    env_file: 
      - .env
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    restart: always
    pull_policy: build
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-p$MARIADB_ROOT_PASSWORD", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    
    
