volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/sschelti/data/wordpress
      o: bind
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/sschelti/data/mariadb
      o: bind

networks:
  inception:

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx-container
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress-container
    restart: always
    env_file: 
      - .env
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb-container
    restart: always
    env_file: 
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception
    
